updates 20190806
Change-Id: I398940f96e0006c5def89bf19d4ff13e85149a71
Signed-off-by: Lenny Verkhovsky <lennyb@mellanox.com>

diff --git a/jenkins/jobs/build-kernel.yaml b/jenkins/jobs/build-kernel.yaml
--- a/jenkins/jobs/build-kernel.yaml
+++ b/jenkins/jobs/build-kernel.yaml
@@ -7,8 +7,8 @@
 - job-template:
     name: 'Build-Kernel'
     node: '{node}'
-    triggers:
-      - timed: '@monthly'
+    #triggers:
+    #  - timed: '@monthly'
     concurrent: false
     parameters:
       - string:
@@ -66,19 +66,12 @@
             version_to_build=${version}
             # Evaluate the latest upstream version
             if [ "$version_to_build" == "latest" ]; then
-                #v=$(lynx --dump https://cdn.kernel.org/pub/linux/kernel/v4.x/ |awk '{print $NF}'|grep patch|grep xz|cut -d'-' -f2|sort -Vr|head -n1)
-                #y=${v%.xz}
-                #version_to_build=$(echo ${y##*/})
                 version_to_build=$( html2text <<< $(wget --output-document - --quiet https://www.kernel.org/ | grep -A 1 "latest_link")|cut -d'[' -f2|cut -d']' -f1)
                 rm -f index.html*
                 echo "Latest version on https://cdn.kernel.org/pub/linux/kernel/v4.x/ is $version_to_build"
 
                 # Evaluate the latest built version
-                #latest=$(basename $(ssh cloudx@13.74.249.42 ls -l /var/www/html/kernel/latest-kernel.src.rpm|awk '{print $NF}'))
-                #latest_built_version=$(echo $latest|cut -d'-' -f2)
-                #echo "********************"
                 latest_built_version=$(ls -l $OUTPUT/latest | awk '{print $NF}' | rev | cut -d'/' -f1|rev)
-                #latest_built_version=$(dirname $(ls -l $OUTPUT/latest-kernel.x86_64.rpm | awk '{print $NF}')|rev | cut -d'/' -f1|rev)
                 echo "latest_built_version=$latest_built_version version_to_build=$version_to_build"
                 if [ ! -z $latest_built_version ]; then
                     if ! version_gt $version_to_build $latest_built_version; then
@@ -90,33 +83,45 @@
 
             fi
 
-            echo "Downloading kernel $version_to_build from https://cdn.kernel.org/pub/linux/kernel/v4.x/"
-            wget $(lynx --dump https://www.kernel.org/|grep ${version_to_build}|grep 'tar.gz'|awk '{print $NF}') 2>&1|tee > /dev/null
+
+            sudo rm -rf linux-*
+            echo "Downloading kernel $version_to_build from https://www.kernel.org/"
+            wget $(lynx --dump https://www.kernel.org/|grep ${version_to_build}|grep 'tar\.'|head -n1|awk '{print $NF}') 2>&1|tee > /dev/null
+            if [ "$?" -ne 0 ]; then
+                echo "ERROR. please check this file exists"
+                echo "$(lynx --dump https://www.kernel.org/|grep ${version_to_build}|grep 'tar.gz'|awk '{print $NF}')"
+                exit 1
+            fi
             log=$LOGDIR/kernel-${version_to_build}.log
-            rm -rf linux-*
-            #wget https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-${version_to_build}.tar.xz 2>&1|tee > /dev/null
             tar xvf $(ls -1 *${version_to_build}*) 2>&1|tee > /dev/null
 
             cd *${version_to_build}*
-            sudo scripts/kconfig/merge_config.sh -n /boot/config-$(uname -r)
+            sudo scripts/kconfig/merge_config.sh -n /home_stack/config-4.18.0-32.el8.x86_64
+            #sudo scripts/kconfig/merge_config.sh -n /boot/config-$(uname -r)
             sudo chown -R $(whoami) .
             for config in "CONFIG_DELL_SMBIOS_WMI=y" "CONFIG_DELL_SMBIOS_SMM=y" "CONFIG_DEVMEM=y"; do
                 echo $config >> .config
             done
             echo "Bulding kernel. Log details $NODE_NAME:/$log"
             pwd
-            echo "make rpm-pkg -j4 > $log"
-            make rpm-pkg -j4 2>&1|tee > $log
+            echo "make rpm-pkg -j4 -s > $log"
+            sudo make rpm-pkg -j4 -s 2>&1|tee > $log
 
             status=$?
             tail -n300 $log
-            mkdir -p $OUTPUT/$version_to_build
 
             if [ "$status" -eq 0 ]; then
+                tmp="/tmp/$$"
+                mkdir $tmp
                 for file in $(tail -n 20 $log|grep 'Wrote:' | awk '{print $2}'); do
-                    cp $file $OUTPUT/$version_to_build
+                    sudo mv $file $tmp
                 done
+                sudo chown stack -R $tmp
+                mkdir -p $OUTPUT
+                mv $tmp $OUTPUT/$version_to_build
                 ln -snf $OUTPUT/$version_to_build $OUTPUT/latest
                 rm -rf /home_kernel/linux-${version_to_build}*
             fi
+            echo "See $OUTPUT"
+            ls $OUTPUT
             exit $status
